# Generated by Django 2.2.6 on 2019-10-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField(verbose_name='frame')),
                ('timestamp', models.DateTimeField(verbose_name='time')),
                ('person_id', models.IntegerField(verbose_name='person_id')),
                ('target', models.CharField(max_length=128, verbose_name='target')),
                ('pos_x', models.FloatField(verbose_name='pos_x')),
                ('pos_y', models.FloatField(verbose_name='pos_y')),
                ('dir_x', models.FloatField(verbose_name='dir_x')),
                ('dir_y', models.FloatField(verbose_name='dir_y')),
            ],
        ),
    ]
