# Generated by Django 2.2.6 on 2019-10-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jalo_display', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person_entry',
            table='target_data',
        ),
    ]
